export const newsList = [
    {
        id: 1,
        type: 1,
        state: 1,
        title: "News 1",
        description: "",
        documentUrl: "",
        testUrl: "",
    },
    {
        id: 2,
        type: 1,
        state: 1,
        title: "News 2",
        description: "",
        documentUrl: "",
        testUrl: "",
    },
    {
        id: 3,
        type: 1,
        state: 1,
        title: "News 3",
        description: "",
        documentUrl: "",
        testUrl: "",
    },
    {
        id: 4,
        type: 1,
        state: 1,
        title: "News 4",
        description: "",
        documentUrl: "",
        testUrl: "",
    },{
        id: 5,
        type: 1,
        state: 1,
        title: "News 5",
        description: "",
        documentUrl: "",
        testUrl: "",
    },
    {
        id: 6,
        type: 1,
        state: 1,
        title: "News 6",
        description: "",
        documentUrl: "",
        testUrl: "",
    },{
        id: 7,
        type: 1,
        state: 1,
        title: "News 7",
        description: "",
        documentUrl: "",
        testUrl: "",
    },
    {
        id: 8,
        type: 1,
        state: 1,
        title: "News 8",
        description: "",
        documentUrl: "",
        testUrl: "",
    },
    {
        id: 9,
        type: 1,
        state: 1,
        title: "News 9",
        description: "",
        documentUrl: "",
        testUrl: "",
    }
]
